/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SellRouteImport } from './routes/sell'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as CheckoutIdRouteImport } from './routes/checkout.$id'

const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIdRoute = CheckoutIdRouteImport.update({
  id: '/checkout/$id',
  path: '/checkout/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/marketplace': typeof MarketplaceRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/verification': typeof VerificationRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/profile/$id': typeof ProfileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/marketplace': typeof MarketplaceRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/verification': typeof VerificationRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/profile/$id': typeof ProfileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/marketplace': typeof MarketplaceRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/verification': typeof VerificationRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/profile/$id': typeof ProfileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/marketplace'
    | '/sell'
    | '/settings'
    | '/verification'
    | '/checkout/$id'
    | '/listing/$id'
    | '/profile/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/marketplace'
    | '/sell'
    | '/settings'
    | '/verification'
    | '/checkout/$id'
    | '/listing/$id'
    | '/profile/$id'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/marketplace'
    | '/sell'
    | '/settings'
    | '/verification'
    | '/checkout/$id'
    | '/listing/$id'
    | '/profile/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  MarketplaceRoute: typeof MarketplaceRoute
  SellRoute: typeof SellRoute
  SettingsRoute: typeof SettingsRoute
  VerificationRoute: typeof VerificationRoute
  CheckoutIdRoute: typeof CheckoutIdRoute
  ListingIdRoute: typeof ListingIdRoute
  ProfileIdRoute: typeof ProfileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$id': {
      id: '/checkout/$id'
      path: '/checkout/$id'
      fullPath: '/checkout/$id'
      preLoaderRoute: typeof CheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  MarketplaceRoute: MarketplaceRoute,
  SellRoute: SellRoute,
  SettingsRoute: SettingsRoute,
  VerificationRoute: VerificationRoute,
  CheckoutIdRoute: CheckoutIdRoute,
  ListingIdRoute: ListingIdRoute,
  ProfileIdRoute: ProfileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
